# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(148, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -10, 147, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Name_edit = QtWidgets.QLineEdit(self.tab)
        self.Name_edit.setObjectName("Name_edit")
        self.verticalLayout.addWidget(self.Name_edit)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.Middle_Name_edit = QtWidgets.QLineEdit(self.tab)
        self.Middle_Name_edit.setObjectName("Middle_Name_edit")
        self.verticalLayout.addWidget(self.Middle_Name_edit)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Surname_edit = QtWidgets.QLineEdit(self.tab)
        self.Surname_edit.setObjectName("Surname_edit")
        self.verticalLayout.addWidget(self.Surname_edit)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.Birthday_edit = QtWidgets.QDateEdit(self.tab)
        self.Birthday_edit.setCalendarPopup(True)
        self.Birthday_edit.setObjectName("Birthday_edit")
        self.verticalLayout.addWidget(self.Birthday_edit)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.Login_edit = QtWidgets.QLineEdit(self.tab)
        self.Login_edit.setObjectName("Login_edit")
        self.verticalLayout.addWidget(self.Login_edit)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.Password_edit = QtWidgets.QLineEdit(self.tab)
        self.Password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_edit.setObjectName("Password_edit")
        self.verticalLayout.addWidget(self.Password_edit)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.Email_edit = QtWidgets.QLineEdit(self.tab)
        self.Email_edit.setObjectName("Email_edit")
        self.verticalLayout.addWidget(self.Email_edit)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.Phone_edit = QtWidgets.QLineEdit(self.tab)
        self.Phone_edit.setObjectName("Phone_edit")
        self.verticalLayout.addWidget(self.Phone_edit)
        self.SignUp_btn = QtWidgets.QPushButton(self.tab)
        self.SignUp_btn.setObjectName("SignUp_btn")
        self.verticalLayout.addWidget(self.SignUp_btn)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Login_edit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.Login_edit_2.setObjectName("Login_edit_2")
        self.verticalLayout_2.addWidget(self.Login_edit_2)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Password_edit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.Password_edit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_edit_2.setObjectName("Password_edit_2")
        self.verticalLayout_2.addWidget(self.Password_edit_2)
        self.SignIn_btn = QtWidgets.QPushButton(self.tab_2)
        self.SignIn_btn.setObjectName("SignIn_btn")
        self.verticalLayout_2.addWidget(self.SignIn_btn)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Middle Name"))
        self.label_5.setText(_translate("MainWindow", "Surname"))
        self.label_10.setText(_translate("MainWindow", "Birthday"))
        self.Birthday_edit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_6.setText(_translate("MainWindow", "Login"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.label_8.setText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "Phone"))
        self.SignUp_btn.setText(_translate("MainWindow", "Sign Up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sign Up"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.SignIn_btn.setText(_translate("MainWindow", "Sign In"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sign In"))
